name: split_smart_api
description: A Dart API Client for the Split Smart API.
version: 1.0.0

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
