name: split_smart_api
description: A Dart API Client for the Split Smart API.
version: 1.0.0

environment:
  sdk: ^3.5.2

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
