name: auth_repository
description: A Dart Repository which manages authentication.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  split_smart_api:
    path: ../split_smart_api
  user_repository:
    path: ../user_repository
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
