name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  split_smart_api:
    path: ../split_smart_api

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
